### ISSUE TITLE
从没有成功下载过解读数据

### ISSUE THREAD

**Issue by bboyendless** [Septillion/CellularInfo-iOS#2]
4G网络下，解读页面停留下载约20分钟（亮屏）
wifi网络下，解读页面停留下载约30分钟（亮屏）
4G网络下，解读页面点下载后，退后台
wifi网络下，解读页面点下载后，退后台

上述情况均无法获取解读数据

**Comment by Septillion** [comment]
我了解到有些用户有这种情况，但暂时还无法复现。未来考虑增加一些错误提示来确认究竟问题出在哪里。

发自我的iPhone

在 2020年12月4日，14:22，young <notifications@github.com> 写道：

﻿

4G网络下，解读页面停留下载约20分钟（亮屏）
wifi网络下，解读页面停留下载约30分钟（亮屏）
4G网络下，解读页面点下载后，退后台
wifi网络下，解读页面点下载后，退后台

上述情况均无法获取解读数据

**Comment by bboyendless** [comment]
提个小建议，如果你们可以成功获取数据，那么是否可以以快照（一天或更久更新）的形式，下发给用户，减少用户的下载时间和下载量

**Comment by Septillion** [comment]
我确实是这样打算的，这个功能需要一段时间来部署。

感谢建议

发自我的iPhone

在 2020年12月4日，17:45，young <notifications@github.com> 写道：

﻿

提个小建议，如果你们可以成功获取数据，那么是否可以以快照（一天或更久更新）的形式，下发给用户，减少用户的下载时间和下载量

**Comment by bboyendless** [comment]
that's cool！！

**Comment by is0bnd** [comment]
两个小建议
1.使用CoreData和CloudKit, 用数据库存储会更好，可参考https://medium.com/apple-developer-academy-federico-ii/syncing-data-on-ios-devices-with-coredata-and-cloudkit-bed296fc26e0
2.统计页面使用统计数据而不是逐条计算所有的数据

**Comment by Septillion** [comment]
收到，感谢建议！

在 2021年1月4日，上午10:21，is0bnd <notifications@github.com> 写道：

﻿

两个小建议
1.使用CoreData和CloudKit, 用数据库存储会更好，可参考https://medium.com/apple-developer-academy-federico-ii/syncing-data-on-ios-devices-with-coredata-and-cloudkit-bed296fc26e0<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmedium.com%2Fapple-developer-academy-federico-ii%2Fsyncing-data-on-ios-devices-with-coredata-and-cloudkit-bed296fc26e0&data=04%7C01%7C%7C3c7d09ec0831416986f208d8b05777a6%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637453236999399139%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=IgP%2FypljwbcO6WPGbxoMaqN%2BmtidkH%2BwICW4ewYqBdE%3D&reserved=0>
2.统计页面使用统计数据而不是逐条计算所有的数据
